/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PictureId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MessageId = IDL.Nat;
export const EmojiId = IDL.Text;
export const Emoji = IDL.Record({
  'id' : EmojiId,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
});
export const UserId = IDL.Text;
export const Time = IDL.Int;
export const MediaType = IDL.Variant({
  'gif' : IDL.Null,
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const MediaFile = IDL.Record({
  'id' : IDL.Nat,
  'blob' : ExternalBlob,
  'fileName' : IDL.Text,
  'mediaType' : MediaType,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'userId' : UserId,
  'customEmojis' : IDL.Vec(EmojiId),
  'timestamp' : Time,
  'mediaFiles' : IDL.Vec(MediaFile),
});
export const Theme = IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null });
export const UserProfile = IDL.Record({
  'theme' : Theme,
  'username' : IDL.Text,
  'usernameColor' : IDL.Text,
  'profilePictureId' : PictureId,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDefaultPicture' : IDL.Func([ExternalBlob, PictureId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMessage' : IDL.Func([MessageId], [], []),
  'getAllEmojis' : IDL.Func([], [IDL.Vec(Emoji)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllMessagesMedia' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Message, IDL.Vec(MediaFile)))],
      ['query'],
    ),
  'getAnonymousCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDefaultPicture' : IDL.Func(
      [PictureId],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getEmojiById' : IDL.Func([EmojiId], [IDL.Opt(Emoji)], ['query']),
  'getEmojiCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMediaById' : IDL.Func([IDL.Nat], [IDL.Opt(MediaFile)], ['query']),
  'getMediaCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMessagesSince' : IDL.Func([MessageId], [IDL.Vec(Message)], ['query']),
  'getRecentMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'initializeDefaults' : IDL.Func(
      [IDL.Vec(IDL.Tuple(PictureId, ExternalBlob))],
      [],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'join' : IDL.Func([IDL.Text, PictureId, IDL.Text], [UserId], []),
  'listDefaultPictures' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(PictureId, ExternalBlob))],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func(
      [IDL.Text, UserId, IDL.Vec(IDL.Nat), IDL.Vec(EmojiId)],
      [MessageId],
      [],
    ),
  'updateThemePreference' : IDL.Func([UserId, Theme], [], []),
  'updateUserProfile' : IDL.Func(
      [UserId, IDL.Text, PictureId, IDL.Text],
      [],
      [],
    ),
  'uploadEmoji' : IDL.Func([ExternalBlob, IDL.Text], [EmojiId], []),
  'uploadMedia' : IDL.Func([ExternalBlob, MediaType, IDL.Text], [IDL.Nat], []),
  'uploadProfilePicture' : IDL.Func([ExternalBlob, PictureId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PictureId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MessageId = IDL.Nat;
  const EmojiId = IDL.Text;
  const Emoji = IDL.Record({
    'id' : EmojiId,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
  });
  const UserId = IDL.Text;
  const Time = IDL.Int;
  const MediaType = IDL.Variant({
    'gif' : IDL.Null,
    'video' : IDL.Null,
    'image' : IDL.Null,
  });
  const MediaFile = IDL.Record({
    'id' : IDL.Nat,
    'blob' : ExternalBlob,
    'fileName' : IDL.Text,
    'mediaType' : MediaType,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'userId' : UserId,
    'customEmojis' : IDL.Vec(EmojiId),
    'timestamp' : Time,
    'mediaFiles' : IDL.Vec(MediaFile),
  });
  const Theme = IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null });
  const UserProfile = IDL.Record({
    'theme' : Theme,
    'username' : IDL.Text,
    'usernameColor' : IDL.Text,
    'profilePictureId' : PictureId,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDefaultPicture' : IDL.Func([ExternalBlob, PictureId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMessage' : IDL.Func([MessageId], [], []),
    'getAllEmojis' : IDL.Func([], [IDL.Vec(Emoji)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllMessagesMedia' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Message, IDL.Vec(MediaFile)))],
        ['query'],
      ),
    'getAnonymousCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDefaultPicture' : IDL.Func(
        [PictureId],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getEmojiById' : IDL.Func([EmojiId], [IDL.Opt(Emoji)], ['query']),
    'getEmojiCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMediaById' : IDL.Func([IDL.Nat], [IDL.Opt(MediaFile)], ['query']),
    'getMediaCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMessagesSince' : IDL.Func([MessageId], [IDL.Vec(Message)], ['query']),
    'getRecentMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'initializeDefaults' : IDL.Func(
        [IDL.Vec(IDL.Tuple(PictureId, ExternalBlob))],
        [],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'join' : IDL.Func([IDL.Text, PictureId, IDL.Text], [UserId], []),
    'listDefaultPictures' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(PictureId, ExternalBlob))],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Text, UserId, IDL.Vec(IDL.Nat), IDL.Vec(EmojiId)],
        [MessageId],
        [],
      ),
    'updateThemePreference' : IDL.Func([UserId, Theme], [], []),
    'updateUserProfile' : IDL.Func(
        [UserId, IDL.Text, PictureId, IDL.Text],
        [],
        [],
      ),
    'uploadEmoji' : IDL.Func([ExternalBlob, IDL.Text], [EmojiId], []),
    'uploadMedia' : IDL.Func(
        [ExternalBlob, MediaType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'uploadProfilePicture' : IDL.Func([ExternalBlob, PictureId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };