/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Emoji {
  'id' : EmojiId,
  'blob' : ExternalBlob,
  'name' : string,
}
export type EmojiId = string;
export type ExternalBlob = Uint8Array;
export interface MediaFile {
  'id' : bigint,
  'blob' : ExternalBlob,
  'fileName' : string,
  'mediaType' : MediaType,
}
export type MediaType = { 'gif' : null } |
  { 'video' : null } |
  { 'image' : null };
export interface Message {
  'id' : MessageId,
  'content' : string,
  'userId' : UserId,
  'customEmojis' : Array<EmojiId>,
  'timestamp' : Time,
  'mediaFiles' : Array<MediaFile>,
}
export type MessageId = bigint;
export type PictureId = string;
export type Theme = { 'dark' : null } |
  { 'light' : null };
export type Time = bigint;
export type UserId = string;
export interface UserProfile {
  'theme' : Theme,
  'username' : string,
  'usernameColor' : string,
  'profilePictureId' : PictureId,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDefaultPicture' : ActorMethod<[ExternalBlob, PictureId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMessage' : ActorMethod<[MessageId], undefined>,
  'getAllEmojis' : ActorMethod<[], Array<Emoji>>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllMessagesMedia' : ActorMethod<[], Array<[Message, Array<MediaFile>]>>,
  'getAnonymousCount' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDefaultPicture' : ActorMethod<[PictureId], [] | [ExternalBlob]>,
  'getEmojiById' : ActorMethod<[EmojiId], [] | [Emoji]>,
  'getEmojiCount' : ActorMethod<[], bigint>,
  'getMediaById' : ActorMethod<[bigint], [] | [MediaFile]>,
  'getMediaCount' : ActorMethod<[], bigint>,
  'getMessageCount' : ActorMethod<[], bigint>,
  'getMessagesSince' : ActorMethod<[MessageId], Array<Message>>,
  'getRecentMessages' : ActorMethod<[bigint], Array<Message>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'initializeDefaults' : ActorMethod<
    [Array<[PictureId, ExternalBlob]>],
    undefined
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'join' : ActorMethod<[string, PictureId, string], UserId>,
  'listDefaultPictures' : ActorMethod<[], Array<[PictureId, ExternalBlob]>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<
    [string, UserId, Array<bigint>, Array<EmojiId>],
    MessageId
  >,
  'updateThemePreference' : ActorMethod<[UserId, Theme], undefined>,
  'updateUserProfile' : ActorMethod<
    [UserId, string, PictureId, string],
    undefined
  >,
  'uploadEmoji' : ActorMethod<[ExternalBlob, string], EmojiId>,
  'uploadMedia' : ActorMethod<[ExternalBlob, MediaType, string], bigint>,
  'uploadProfilePicture' : ActorMethod<[ExternalBlob, PictureId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];